FROM python:3.7
EXPOSE 5000
COPY . /command
WORKDIR /command
RUN pip install -r /command/requirements.txt
#RUN pip install -r /command/requirements.txt

#RUN flask db init
#RUN flask db migrate

ENTRYPOINT ["python"]
CMD ["command.py", "--host=0.0.0.0"]
CMD ["file_migrator.py"]